### ISSUE TITLE
Upgrading from NSpec 3.0.7 to 3.1 throws "System.MissingMethodException : Method not found: 'Void NSpec.Domain.Context..ctor(System.String, System.String, Boolean)'."

### ISSUE THREAD

**Issue by johnhamm** [provegard/NSpecInNUnit#9]
I am using NSpec's NetFramework sample:
NSpec: 3.1
NSpecInNUnit: 3.1
NUnit: 3.9

Test Name:	RealizeSpec
Test FullName:	LibrarySpecs.ConstantGeneratorTest.RealizeSpec
Test Source:	 : line 0
Test Outcome:	Failed
Test Duration:	0:00:00.003

Result StackTrace:	
```
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(IMethodInfo method)
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
--MissingMethodException
   at NSpecInNUnit.nspec_as_nunit`1.Examples()
Result Message:	
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.MissingMethodException : Method not found: 'Void NSpec.Domain.Context..ctor(System.String, System.String, Boolean)'.

```
If I downgrade NSpec to 3.0.7, everything works correctly.

**Comment by provegard** [comment]
Thanks for the report, I'll look into it!

**Comment by provegard** [comment]
I released a new version, 3.2.0. It depends on NUnit 3.9 and NSpec 3.1. Can you please test it?

**Comment by johnhamm** [comment]
Wow that was fast - trying it now.

**Comment by johnhamm** [comment]
That fixed the issue.  Nice job.

**Comment by johnhamm** [comment]
Now if you can ssssssomehow get NSpecInNUnit to be compatible with Resharper's dotCover's continuous integration, that would be the missing link!

**Comment by provegard** [comment]
If you mean running impacted/dirty tests in the background, then that depends on #8.
